### ISSUE TITLE
1.10 breaks builds in es modules: Uncaught Error: Dynamic require of "./add.js" is not supported

### ISSUE THREAD

**Issue by simlevesque** [piercus/kalman-filter#36]
```
chunk-ACCAMVX6.js?v=399176e3:12 Uncaught Error: Dynamic require of "./add.js" is not supported
    at chunk-ACCAMVX6.js?v=399176e3:12:9
    at index.js:5:14
    at Array.forEach (<anonymous>)
    at ../node_modules/kalman-filter/lib/linalgebra/index.js (index.js:4:9)
    at __require2 (chunk-ACCAMVX6.js?v=399176e3:18:50)
    at ../node_modules/kalman-filter/index.js (index.js:14:14)
    at __require2 (chunk-ACCAMVX6.js?v=399176e3:18:50)
    at dep:kalman-filter:1:16
```

A simple revert to 1.9.x fixes the issue. I can't upgrade until this scenario is fixed. Let me know if you need any help.

**Comment by piercus** [comment]
@simlevesque sorry for the regression, and thanks for the notification !

Yeah help would be much appreciated !

If you can create a branch with a unit test that fails it would be great.

Else can you please give me more information about how you are using the package, you are using the browser version ? 

Thanks for your help

**Comment by piercus** [comment]
@simlevesque it looks easy to fix but i would be glad if i can add a unit test for this, to avoid any such regression in the future
